### ISSUE TITLE
a bug report

### ISSUE THREAD

**Issue by naxiaoguang** [Nodlik/react-pageflip#1]
![image](https://user-images.githubusercontent.com/7166587/84645266-e301e800-af32-11ea-8495-25b832cf0865.png)
![image](https://user-images.githubusercontent.com/7166587/84645342-fc0a9900-af32-11ea-8f27-87e2d704e6a2.png)

**Comment by Nodlik** [comment]
Hello! Sorry, but I cannot reproduce this bug. How do you use this component?
The following code works fine:
<img width="375" alt="Снимок экрана 2020-06-15 в 15 10 59" src="https://user-images.githubusercontent.com/6822484/84656330-323c1e80-af1b-11ea-9e78-e8c5163b856e.png">
<img width="378" alt="Снимок экрана 2020-06-15 в 15 11 04" src="https://user-images.githubusercontent.com/6822484/84656482-6fa0ac00-af1b-11ea-8df7-afe9a3dc3cef.png">
Also try adding `"noImplicitAny": false` to your tsconfig.json

**Comment by naxiaoguang** [comment]
![image](https://user-images.githubusercontent.com/7166587/84727971-d0cf8a80-afc2-11ea-954c-137f8f31d2dd.png)

```
 <React.StrictMode>
            <HTMLFlipBook/>
 <React.StrictMode/>
```
worked well!
another bug. when flip from next to pre page, pre page`s content appeared. it`s ok from pre to next ;
