### ISSUE TITLE
How can I achieve double-page mode?

### ISSUE THREAD

**Issue by roshie** [Nodlik/react-pageflip#19]
I'm using the code, which is in the example. 
```
<HTMLFlipBook width={300} height={500}>
    <div className="Page">Page 1</div>
    <div className="Page">Page 2</div>
    <div className="Page">Page 3</div>
    <div className="Page">Page 4</div>
</HTMLFlipBook>
```
I don't have a 'showCover' prop (Which means, it defaults to false). But still, the flip-book shows in single-page mode. How can I achieve this?

**Comment by RareSecond** [comment]
@roshie Did you ever manage to solve this issue?

**Comment by roshie** [comment]
The issue was because, I had a parent container that was contracting the HTMLFlipBook component's width. Removing that container solved my issue.
