### ISSUE TITLE
Cannot use import statement outside a module - Next.JS

### ISSUE THREAD

**Issue by jonrrivera** [Nodlik/react-pageflip#4]
Hi,

I just installed this and the npm package is giving me this error. Please advise. 

<img width="776" alt="Screen Shot 2020-08-14 at 12 58 55 PM" src="https://user-images.githubusercontent.com/18686388/90288115-31563900-de47-11ea-9b91-79beb6e9de6e.png">

<img width="1202" alt="Screen Shot 2020-08-14 at 1 00 07 PM" src="https://user-images.githubusercontent.com/18686388/90288143-3e732800-de47-11ea-89b5-f1b4856a1952.png">

**Comment by Nodlik** [comment]
Hmm, I think I've fixed that now.
Please update the libraries (page-flip and react-pageflip) to the latest version and try again. Also restart next.js server.

**Comment by jonrrivera** [comment]
fixed! really appreciate it. Will share the project once finished.
