### ISSUE TITLE
Missing styles on basic example.

### ISSUE THREAD

**Issue by augmentaudio** [Nodlik/react-pageflip#7]
The basic example on your documentation works but without most of the styles. The page turn effect works but missing box-shadows from --left and --right and none of the Sass rules from the stPageFlip demo seem to be there. Would be super useful to include a working example in this main repo, otherwise the wrapper seems to work great !

**Comment by jonportelli** [comment]
The demo styles are not included in these docs or repo but you just need to install sass and then copy over styles over from the other demo here. https://nodlik.github.io/StPageFlip/demo.html

**Comment by augmentaudio** [comment]
That worked perfectly, thanks !

**Comment by eltongonc** [comment]
Amazing plugin man 👍

I ran into some layout issues. But the following code did the trick
```css
* {
  box-sizing: border-box;
}
```
