### ISSUE TITLE
No dynamic resizing?

### ISSUE THREAD

**Issue by th1rst** [Nodlik/react-pageflip#9]
It seems like the Flipbook gets its dimensions once on componendDidMount and then never updates (except for Page Refresh) when resizing the Window. So it seems like there is no option to dynamically resize. Am I correct and this is wanted behavior or is it an error on my end?

**Comment by Nodlik** [comment]
Fixed

**Comment by srtfisher** [comment]
I don't believe this is fixed, sadly. The CSS `width` style attribute is set on the flipbook children and doesn't update on resize. Setting the flipbook's `key` equal to the page's width (forcing it to re-render) does fix it.

**Comment by cdk0507** [comment]
@srtfisher 
Is there any way to keep the pageNumber on force rendering?
I'm trying to use onInit, but I'm not sure.
thank you.
